frontend:
	bash component/frontend.sh

catalogue:
	bash component/catalogue.sh

mongodb:
	bash component/mongodb.sh

redis:
	bash component/redis.sh 

user:
	bash component/user.sh 

cart:
	bash component/cart.sh

mysql:
	bash component/mysql.sh

shipping:
	bash component/shipping.sh

rabbitmq:
	bash component/rabbitmq.sh 

payment:
	bash component/payment.sh